#!/bin/bash


mkdir -p /var/www/html
mkdir -p /var/log/supervisor


rm -rf /var/www/html

cp -r /home/ttrss /var/www/html
cp /home/config.php /var/www/html

#php /home/configure-db.php
rm -r /home/ttrss /home/config.php

cd /var/www/html

chown -R www-data:www-data  /var/www

chmod -R 755 /var/www/html/cache/images
chmod -R 755 /var/www/html/cache/upload
chmod -R 755 /var/www/html/cache/export
chmod -R 755 /var/www/html/cache/js
chmod -R 755 /var/www/html/feed-icons /var/www/html/lock


sed -i -e "s#ENVDBTYPE#$DB_TYPE#g" config.php
sed -i -e "s#ENVDBHOST#$DB_HOST#"  config.php
sed -i -e "s#ENVDBUSER#$DB_USER#"  config.php
sed -i -e "s#ENVDBNAME#$DB_NAME#"  config.php
sed -i -e "s#ENVDBPASS#$DB_PASS#"  config.php
sed -i -e "s#ENVDBPORT#$DB_PORT#"  config.php
sed -i -e "s#ENVURLPATH#$URL_PATH#" config.php



if ! mysql -u $DB_USER -h ${DB_HOST} -p${DB_PASS} -e "USE ${DB_NAME}; SHOW TABLES;"|grep "ttrss_users"; then
    date
    echo "Creating..."
    /usr/bin/mysql -u $DB_USER -h ${DB_HOST} -p${DB_PASS} -e "
        USE ${DB_NAME};
        SOURCE /var/www/html/schema/ttrss_schema_mysql.sql;"
else
    date
    echo "${DB_NAME} already present"
fi


echo "Creating database:"

cd /var/www/html
sudo -u www-data ./update.php --update-schema
sudo -u www-data ./update.php --indexes

exec supervisord -n
